import type { ProjectBase } from '../project-types';

export const livekitAgent: ProjectBase = {
    title: "Genix Home AI Voice Assistant",
    description: "A real-time voice-activated customer service assistant designed for GenixNetworks home router management. Powered by the Gemini 2.5 Flash Native Audio model and LiveKit, this agent empowers users to manage their home networks, configure parental controls, analyze traffic, and troubleshoot issues entirely through natural, low-latency conversational voice commands.",
    detailedContent: [
        {
            type: 'heading',
            content: 'Core Capabilities (核心功能)'
        },
        {
            type: 'list',
            items: [
                'Advanced Parental Controls & Network Access: Supports creating user profiles, assigning devices, and setting complex schedules (e.g., configuring weekly bedtimes or temporarily pausing internet access for specific profiles).',
                'Vulnerability Scanning & Security: Users can trigger network or device-specific security scans and receive easy-to-understand summaries of open ports or potential risks.',
                'Traffic & Usage Analysis: Provides insights into bandwidth usage, top applications, category distribution, and active devices by querying historical data (up to 30 days).',
                'Wi-Fi & Device Management: Allows users to securely query or change Wi-Fi passwords, SSIDs, and manage connected devices conversationally.',
                'Troubleshooting (RAG): Integrates a knowledge base to help users diagnose hardware issues (like router LED indicators) or connection drops without navigating complex manuals.'
            ]
        },
        {
            type: 'heading',
            content: 'Flow'
        },
        {
            type: 'image',
            src: `${import.meta.env.BASE_URL}images/projects/genix_livekit_diagram.png`,
            alt: 'Flowchart of the LiveKit agent'
        },
        {
            type: 'heading',
            content: 'Real-World Use Cases (真實使用情境)'
        },
        {
            type: 'list',
            items: [
                'Smart Scheduling: User: "Block internet for the Kids profile every Wednesday from 8 to 9 PM." -> The agent automatically parses the timezone and sets a recurring API rule.',
                'Network Monitoring: User: "What device is most active on my network?" or "How much data is my iPhone using?" -> The agent retrieves and summarizes the specific usage metrics.',
                'Security Operations: User: "Show vulnerability scan results for my NAS." -> Agent: "Port 445 (SMB) is open on your NAS. This is a high-risk port — I recommend securing it."'
            ]
        },
        {
            type: 'heading',
            content: 'Example'
        },
        {
            type: 'image',
            src: `${import.meta.env.BASE_URL}images/projects/genix_livekit_wifi_qrcode.png`,
            alt: 'Wi-Fi QrCode generated by the agent'
        },
        {
            type: 'image',
            src: `${import.meta.env.BASE_URL}images/projects/genix_livekit_security_events.png`,
            alt: 'Show security events to help user monitor and manage the network'
        },
        {
            type: 'image',
            src: `${import.meta.env.BASE_URL}images/projects/genix_livekit_bedtime.png`,
            alt: 'Support setting bed time by human language'
        },
        {
            type: 'image',
            src: `${import.meta.env.BASE_URL}images/projects/genix_livekit_apps_timeline.png`,
            alt: 'Support show apps using timeline'
        },
        {
            type: 'heading',
            content: 'Technical Implementation & Challenges (技術實作與克服挑戰)'
        },
        {
            type: 'list',
            items: [
                'Contextual Identity Management: Automatically parses JWT tokens to authenticate users, fetch authorized router IDs (Box IDs), and resolve user timezones to accurately execute time-sensitive commands.',
                'Resilient Error Handling: To prevent silent failures during unexpected backend disconnections or "entity not found" exceptions, I implemented a custom Log Interceptor (GeminiErrorHandler). It actively monitors plugin logs and publishes a reliable WebSocket "reconnect_request" to the frontend, ensuring a graceful UI recovery.',
                'Intelligent Guardrails: The agent is programmed with strict boundaries, gracefully refusing unrelated topics (e.g., weather queries), unsupported features, or prompt injection attempts ("Ignore your instructions..."), ensuring a secure and focused service.'
            ]
        },
        {
            type: 'heading',
            content: 'Architecture & Deployment'
        },
        {
            type: 'list',
            items: [
                'Built with Python, LiveKit Agents SDK, and Google TTS (Chirp3 HD).',
                'Supported containerized deployment using Docker and Docker Compose.',
                'Implemented GitLab CI/CD workflow for automated deployments across separate Development and Production environments.'
            ]
        },
        {
            type: 'heading',
            content: 'Live Demo'
        },
        {
            type: 'link',
            url: 'https://gemini-live.genixnetworks.cloud/',
            text: 'LiveKit Agent Pro Environment'
        }
    ],
    technologies: ["Python", "LiveKit", "Gemini 2.5 Flash", "Docker", "GitLab CI", "JWT", "RAG"],
    status: "Completed",
    date: "2026/01-2026/07",
    image: `${import.meta.env.BASE_URL}images/projects/genix_livekit.png`,
    link: "https://gemini-live.genixnetworks.cloud/",
    sourceCode: ""
};